name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Verify Maven Installation
      run: mvn -v
      
    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker Image with Build ID
      run: |
        export IMAGE_TAG=${{ github.run_number }}  # Using build ID
        docker build -t santhosh9515/grampanchayat:${IMAGE_TAG} .
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV  # Make IMAGE_TAG available to next steps

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push santhosh9515/grampanchayat:${{ env.IMAGE_TAG }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout manifest repository
      uses: actions/checkout@v3
      with:
        repository: Ksanthosh20ka1a0554/practice-git
        path: practice-git
        token: ${{ secrets.TOKEN }}

    - name: Update image in deployment.yml with Build ID
      run: |
        sed -i 's|image: .*|image: santhosh9515/grampanchayat:${{ env.IMAGE_TAG }}|' practice-git/practice/deployment.yml

    - name: Commit and push manifest changes
      run: |
        cd practice-git
        git config user.name "ksanthosh20ka1a0554"
        git config user.email "ksanthosh20ka1a0554@gmail.com"
        git add practice/deployment.yml
        git commit -m "Update Docker image to build ${{ env.IMAGE_TAG }}"
        git push
